# -*- coding: utf-8 -*-
"""Tarea_3_José Luis Romero Vazquez.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wEVrF97WBb2_o9hyK_OZryOWNmnwa6f6

**Tarea 03**<BR>
**José Luis Romero Vázquez**<BR>
**GRAFOS COLOREADOS**
"""

import networkx as nx
import matplotlib.pyplot as plt

# Define el grafo dual basado en el diagrama proporcionado
dual_graph = nx.Graph()

# Agrega los nodos correspondientes a las regiones (A, C, E, G, M, O, Q)
regions = ["A", "C", "E", "G", "M", "O", "Q"]
dual_graph.add_nodes_from(regions)

# Agrega aristas entre regiones adyacentes
edges = [("A", "C"), ("A", "E"), ("A", "G"), ("C", "E"), ("E", "M"), ("E", "Q"), ("G", "Q"), ("M", "Q"), ("M", "O")]
dual_graph.add_edges_from(edges)

# Muestra el grafo dual
pos = nx.spring_layout(dual_graph)
nx.draw(dual_graph, pos, with_labels=True, node_color='lightblue', node_size=500, font_size=10)
plt.title("Grafo Dual")
plt.show()

# Colorea el grafo y determina su número cromático
color_map = nx.coloring.greedy_color(dual_graph, strategy="largest_first")
num_cromatico = max(color_map.values()) + 1  # el número cromático es el máximo color usado + 1

# Muestra el grafo coloreado
colors = [color_map[node] for node in dual_graph.nodes()]
nx.draw(dual_graph, pos, with_labels=True, node_color=colors, node_size=500, font_size=10, cmap=plt.cm.rainbow)
plt.title("Grafo Dual Coloreado (Estrategia: largest_first)")
plt.show()

# Estrategia de coloreado utilizada: largest_first
# Número cromático: num_cromatico

# Repetir el ejercicio usando otra estrategia
color_map_2 = nx.coloring.greedy_color(dual_graph, strategy="random_sequential")
num_cromatico_2 = max(color_map_2.values()) + 1  # el número cromático es el máximo color usado + 1

# Muestra el grafo coloreado con la segunda estrategia
colors_2 = [color_map_2[node] for node in dual_graph.nodes()]
nx.draw(dual_graph, pos, with_labels=True, node_color=colors_2, node_size=500, font_size=10, cmap=plt.cm.rainbow)
plt.title("Grafo Dual Coloreado (Estrategia: random_sequential)")
plt.show()

# Estrategia de coloreado utilizada: random_sequential
# Número cromático: num_cromatico_2