# -*- coding: utf-8 -*-
"""Tarea_2_Jose Luis Romero Vazquez.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ARKJkop_PwD7hAOf-lhx7zUCc_bG-wUg

**Tarea 02**<BR>
**José Luis Romero Vázquez**<BR>
**GRAFOS PLANOS**
"""

import networkx as nx
import matplotlib.pyplot as plt

# Crear el grafo K44
K44 = nx.complete_multipartite_graph(4, 4)

# Muestra el grafo en pantalla
pos = nx.kamada_kawai_layout(K44)
nx.draw(K44, pos)
plt.show()

import networkx as nx
import matplotlib.pyplot as plt

# Crea el grafo K44
K44 = nx.complete_multipartite_graph(4, 4)

# Muestra el grafo en pantalla
pos = nx.kamada_kawai_layout(K44)
nx.draw(K44, pos)
plt.show()

# Verifica el corolario 1 de Planaridad
is_planar, _ = nx.check_planarity(K44)
corolario_1 = is_planar

# El grafo K44 no es planar porque contiene un subgrafo homeomorfo a K5 o K3,3
# Corolario 1 de Planaridad: No se cumple

# Verificar el corolario 2 de Planaridad
n = len(K44.nodes)
m = len(K44.edges)
corolario_2 = m <= 3 * n - 6

# K44 tiene 8 vértices y 16 aristas. Según el corolario 2, un grafo planar con 8 vértices debería tener como máximo 18 aristas.
# Sin embargo, este corolario solo se aplica a grafos planarios, y dado que K44 no es planar, no cumple con el corolario en el sentido de ser aplicable.
# Corolario 2 de Planaridad: No se cumple

# Verificar si es plano con check_planarity y obtener el contraejemplo si no lo es
is_planar, embedding = nx.check_planarity(K44)
if not is_planar:
    print("El grafo no es plano. Aquí está el contraejemplo:")
    # Genera un contraejemplo simple para la visualización
    subgraph = nx.subgraph(K44, [0, 1, 2, 3, 4, 5, 6])
    pos_subgraph = nx.kamada_kawai_layout(subgraph)
    nx.draw(subgraph, pos=pos_subgraph, with_labels=True)
    plt.show()

# Crea el grafo dodecaedro
D = nx.dodecahedral_graph()

# Genera la lista de vértices
nlist = [
    [17, 18, 19, 3, 4],
    [11, 10, 0, 1, 2, 6, 5, 15, 16, 12],
    [9, 8, 7, 14, 13]
]

# Muestra el grafo dodecaedro
pos = nx.kamada_kawai_layout(D)
nx.draw(D, pos)
plt.show()

# Resultados:
# Corolario 1 de Planaridad: No se cumple
# Corolario 2 de Planaridad: No se cumple

import networkx as nx
import matplotlib.pyplot as plt

# Crea el grafo K44
K44 = nx.complete_multipartite_graph(4, 4)

# Muestra el grafo en pantalla
pos = nx.kamada_kawai_layout(K44)
nx.draw(K44, pos)
plt.show()

# Verifica el corolario 1 de Planaridad
is_planar, _ = nx.check_planarity(K44)
corolario_1 = is_planar

# El grafo K44 no es planar porque contiene un subgrafo homeomorfo a K5 o K3,3
# Corolario 1 de Planaridad: No se cumple

# Verifica el corolario 2 de Planaridad
n = len(K44.nodes)
m = len(K44.edges)
corolario_2 = m <= 3 * n - 6

# K44 tiene 8 vértices y 16 aristas. Según el corolario 2, un grafo planar con 8 vértices debería tener como máximo 18 aristas.
# Sin embargo, este corolario solo se aplica a grafos planarios, y dado que K44 no es planar, no cumple con el corolario en el sentido de ser aplicable.
# Corolario 2 de Planaridad: No se cumple

# Verificar si es plano con check_planarity y obtener el contraejemplo si no lo es
is_planar, embedding = nx.check_planarity(K44)
if not is_planar:
    print("El grafo no es plano. Aquí está el contraejemplo:")
    # Generar un contraejemplo simple para la visualización
    subgraph = nx.subgraph(K44, [0, 1, 2, 3, 4, 5, 6])
    pos_subgraph = nx.kamada_kawai_layout(subgraph)
    nx.draw(subgraph, pos=pos_subgraph, with_labels=True)
    plt.show()

# Crea el grafo dodecaedro
D = nx.dodecahedral_graph()

# Genera la lista de vértices
nlist = [
    [17, 18, 19, 3, 4],
    [11, 10, 0, 1, 2, 6, 5, 15, 16, 12],
    [9, 8, 7, 14, 13]
]

# Muestra el grafo dodecaedro usando el layout en shell
nx.draw_shell(D, nlist=nlist, with_labels=True)
plt.show()

# Verifica los corolarios para el grafo dodecaedro
# Verifica el corolario 1 de Planaridad
is_planar, _ = nx.check_planarity(D)
corolario_1_dodecaedro = is_planar

# Verifica el corolario 2 de Planaridad
n_dodecaedro = len(D.nodes)
m_dodecaedro = len(D.edges)
corolario_2_dodecaedro = m_dodecaedro <= 3 * n_dodecaedro - 6

# Verifica si es plano con check_planarity
is_planar_dodecaedro, embedding_dodecaedro = nx.check_planarity(D)

# Resultados:
print("Corolario 1 de Planaridad (K44):", corolario_1)  # False
print("Corolario 2 de Planaridad (K44):", corolario_2)  # False (no se aplica porque el grafo no es planar)
print("Corolario 1 de Planaridad (Dodecaedro):", corolario_1_dodecaedro)  # False
print("Corolario 2 de Planaridad (Dodecaedro):", corolario_2_dodecaedro)  # False
print("El grafo dodecaedro es planar:", is_planar_dodecaedro)  # False