# -*- coding: utf-8 -*-
"""Tarea_6_Jose Luis Romero Vazquez.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mn0UKvKzNHup0Jc55J9wgDq5YXNWn61m

**Tarea 06**<BR>
**José Luis Romero Vázquez**<BR>
**Árbol de expansión mínima**
"""

import networkx as nx
import matplotlib.pyplot as plt

# Crear el grafo
G = nx.Graph()

# Agregar las aristas con sus pesos
edges = [
    (1, 2, 10),
    (1, 5, 45),
    (1, 4, 30),
    (2, 3, 50),
    (2, 5, 40),
    (2, 6, 25),
    (3, 6, 15),
    (4, 6, 30),
    (5, 3, 35),
    (5, 6, 55),

]

G.add_weighted_edges_from(edges)

# Generar el Árbol de Expansión Mínima utilizando el algoritmo de Kruskal
mst = nx.minimum_spanning_tree(G, algorithm='kruskal')

# Dibujar el grafo original
plt.figure(figsize=(10, 8))

pos = nx.spring_layout(G)
nx.draw(G, pos, with_labels=True, node_size=700, node_color='skyblue', font_size=15)
labels = nx.get_edge_attributes(G, 'weight')
nx.draw_networkx_edge_labels(G, pos, edge_labels=labels)

plt.title('Grafo Original')
plt.show()

# Dibujar el Árbol de Expansión Mínima
plt.figure(figsize=(10, 8))

mst_pos = nx.spring_layout(mst)
nx.draw(mst, mst_pos, with_labels=True, node_size=700, node_color='skyblue', font_size=15)
mst_labels = nx.get_edge_attributes(mst, 'weight')
nx.draw_networkx_edge_labels(mst, mst_pos, edge_labels=mst_labels)

plt.title('Árbol de Expansión Mínima')
plt.show()