# -*- coding: utf-8 -*-
"""Tarea_5_JoseLuis Romero Vazquez.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11caMBdYz_fqmNLmSZBZYa-LM8sJyn-p7

**Tarea 05**<BR>
**José Luis Romero Vázquez**<BR>
**Caminos y circuitos Hamiltonianos**
"""

import networkx as nx
import matplotlib.pyplot as plt

def generar_grafo_petersen():
    # 1. Diseñar una función que genere el grafo y lo grafique
    G = nx.petersen_graph()
    pos = nx.spring_layout(G)
    nx.draw(G, pos, with_labels=True, node_color='skyblue', node_size=700, font_weight='bold')
    plt.show()
    return G, pos

def imprimir_orden_y_grado(G):
    # 2. Imprimir en pantalla el orden del grafo (|G|) y el grado de cada uno de los vértices
    print(f"Orden del grafo: {G.number_of_nodes()}")
    print("Grados de los vértices:")
    for node in G.nodes():
        print(f"{node}: {G.degree(node)}")

def revisar_teoremas(G):
    # 3. Revisar el teorema de Ore y el de Dirac y agregar comentarios
    cumple_ore = all(G.degree(u) + G.degree(v) >= G.number_of_nodes() for u, v in nx.non_edges(G))
    cumple_dirac = all(G.degree(node) >= G.number_of_nodes() // 2 for node in G.nodes())

    # Comentarios
    if cumple_ore:
        print("El grafo cumple con el teorema de Ore")
    else:
        print("El grafo no cumple con el teorema de Ore")

    if cumple_dirac:
        print("El grafo cumple con el teorema de Dirac")
    else:
        print("El grafo no cumple con el teorema de Dirac")

def imprimir_camino_hamiltoniano(G):
    # 4. Imprimir en pantalla el camino hamiltoniano del grafo
    try:
        ciclo_hamiltoniano = list(nx.find_cycle(G))
        print("Camino hamiltoniano del grafo:", ciclo_hamiltoniano)
        return ciclo_hamiltoniano
    except nx.exception.NetworkXNoCycle:
        print("No se encontró un camino hamiltoniano en el grafo.")
        return []

def realizar_animacion(G, pos, ciclo_hamiltoniano):
    # 5. Realizar la animación del camino
    if not ciclo_hamiltoniano:
        return

    plt.ion()  # Turn on interactive mode
    fig, ax = plt.subplots()

    edge_colors = ['black'] * len(G.edges())
    edge_list = list(G.edges())

    for i in range(len(ciclo_hamiltoniano)):
        nx.draw(G, pos, with_labels=True, node_color='skyblue', node_size=700, font_weight='bold', edge_color=edge_colors)
        plt.pause(0.5)
        if i < len(ciclo_hamiltoniano) - 1:
            u, v = ciclo_hamiltoniano[i][:2]
            edge_index = edge_list.index((u, v)) if (u, v) in edge_list else edge_list.index((v, u))
            edge_colors[edge_index] = 'blue'

    plt.ioff()  # Turn off interactive mode
    plt.show()

# Ejecutar las funciones
G, pos = generar_grafo_petersen()
imprimir_orden_y_grado(G)
revisar_teoremas(G)
ciclo_hamiltoniano = imprimir_camino_hamiltoniano(G)
realizar_animacion(G, pos, ciclo_hamiltoniano)