# -*- coding: utf-8 -*-
"""Tarea_4_Jose Luis Romero Vazquez.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jPnz_A8oLngUiSRYEXe_LIuQ6hDsO7rk

**Tarea 04**<BR>
**José Luis Romero Vázquez**<BR>
**Caminos más cortos**
"""

pip install matplotlib

import networkx as nx

# 1. Crear el grafo Chvátal dirigido
G = nx.chvatal_graph(nx.DiGraph())

# 2. Generar los pesos de las aristas
for (u, v) in G.edges():
    if u < 3:
        G[u][v]['weight'] = u + 2 * v
    elif u < 7:
        G[u][v]['weight'] = 3 * u + v
    else:
        G[u][v]['weight'] = u + 2 * v

# 3. Consultar la información de las aristas
print(G.edges(data=True))

import networkx as nx
import matplotlib.pyplot as plt

# 1. Crear el grafo Chvátal dirigido
G = nx.chvatal_graph(nx.DiGraph())

# 2. Generar los pesos de las aristas
for (u, v) in G.edges():
    if u < 3:
        G[u][v]['weight'] = u + 2 * v
    elif u < 7:
        G[u][v]['weight'] = 3 * u + v
    else:
        G[u][v]['weight'] = u + 2 * v

# 3. Consultar la información de las aristas
print(G.edges(data=True))

# 4. Mostrar únicamente los vértices del grafo
nlist = [[0], [11, 9, 1, 7, 3, 5, 4], [6, 2, 8, 10]]
pos = nx.shell_layout(G, nlist, 0.26)
nx.draw(G, pos=pos, edgelist=[], with_labels=True, font_weight='bold',
        node_color='skyblue', node_size=310)
plt.show()

# 5. Mostrar las aristas con sus pesos y colores según condición
def showEdges(G, pos):
    edge_colors = ['gray' if G[u][v]['weight'] < 20 else 'green' for u, v in G.edges()]
    edge_labels = {(u, v): G[u][v]['weight'] for u, v in G.edges()}
    nx.draw(G, pos, edgelist=G.edges(), edge_color=edge_colors, with_labels=True,
            font_weight='bold', node_color='skyblue', node_size=310)
    nx.draw_networkx_edge_labels(G, pos, edge_labels=edge_labels)
    plt.show()

showEdges(G, pos)